#theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs
lsi: false
safe: true
disable_disk_cache: BOOL
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
